- name: Telegram Message Notify
  # You may pin to the exact commit or the version.
  # uses: appleboy/telegram-action@12a87fd2ecd83686473a41ea891dcb0896178726
    uses: appleboy/telegram-action@v0.0.8
    with:
        # telegram user
        to: # optional
        # telegram token
        token: # optional
        # telegram message
        message: # optional
        # overwrite the default message template with the contents of the specified file
        message_file: # optional
        # support socks5 proxy URL
        socks5: # optional
        # send the photo message.
        photo: # optional
        # send the document message.
        document: # optional
        # send the sticker message.
        sticker: # optional
        # send the audio message.
        audio: # optional
        # send the voice message.
        voice: # optional
        # send the location message.
        location: # optional
        # send the venue message.
        venue: # optional
        # send the video message.
        video: # optional
        # enable debug mode.
        debug: # optional
        # message format: markdown or html
        format: # optional